### PR TITLE
Azad branch

### PR DESCRIPTION
**Pull request by AzadBatch21**

### CODE REVIEW

**Review by ruslan138 — APPROVED** [review]

**Review by aliya-guliyeva — APPROVED** [review]
well-done

**Review by Ariz023 — APPROVED** [review]
reviewed

**Review by RaufVerdiyev — COMMENTED** [review]
First_proje

**Comment by devruslan** [comment]
Xosum gelmedi amma sensen da

**Review by devruslan — APPROVED** [review]

**Review by RaufVerdiyev — APPROVED** [review]
ARR

**Pull request merged**
